# Generated by Django 4.0.3 on 2023-04-14 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('barcode', models.TextField()),
                ('exp_date', models.TextField()),
                ('size', models.CharField(choices=[('SMALL', 'small'), ('LARGE', 'large')], default='SMALL', max_length=20)),
                ('create_date', models.DateTimeField()),
            ],
        ),
    ]
